packages:
  - clients/js
  - clients/js/type-only-test
  - contracts/
  - examples/hardhat
  - examples/ethersv5-ts-esm
  - examples/ethersv6-ts-esm
  - examples/hardhat-boilerplate
  - examples/hardhat-boilerplate/frontend
  - examples/wagmi-v2
  - examples/onchain-signer
  - integrations/hardhat
  - integrations/wagmi-v2
