[package]
name = "sapphire-paratime"
version = "0.1.5-testnet"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2021"
license = "Apache-2.0"

[package.metadata.orc.release]
runtime-id = "0000000000000000000000000000000000000000000000000000000000000000"

[package.metadata.orc.test]
runtime-id = "000000000000000000000000000000000000000000000000a6d1e3ebf60dff6c"

[package.metadata.fortanix-sgx]
heap-size = 134217728
stack-size = 2097152
threads = 6
debug = false

[dependencies]
cipher-keymanager = { git = "https://github.com/oasisprotocol/cipher-paratime", rev = "1c0094da3d485b33c873078e94efec31f72d85de" }
module-evm = { git = "https://github.com/oasisprotocol/oasis-sdk", rev = "408b8c5f9d2a7aeafaba773effb4bda5f6306a6e", package = "oasis-runtime-sdk-evm" }
oasis-runtime-sdk = { git = "https://github.com/oasisprotocol/oasis-sdk", rev = "408b8c5f9d2a7aeafaba773effb4bda5f6306a6e" }

# Third party.
once_cell = "1.8.0"

[dev-dependencies]
cbor = { version = "0.2.1", package = "oasis-cbor" }
io-context = "0.2.0"

[profile.release]
codegen-units = 1
lto = "thin"
