name: contracts-test
on:
  push:
    paths:
      - 'contracts/**'
      - 'clients/js/**'
    branches:
      - main
  pull_request:
    paths:
      - 'contracts/**'
      - 'clients/js/**'
    branches:
      - main
jobs:
  hardhat-test:
    runs-on: ubuntu-latest
    services:
      sapphire-dev-ci:
        image: ghcr.io/oasisprotocol/sapphire-dev:latest
        ports:
          - 8545:8545
          - 8546:8546
        env:
          OASIS_DEPOSIT: /oasis-deposit -to test\ test\ test\ test\ test\ test\ test\ test\ test\ test\ test\ junk -n 20
        options: >-
          --rm
          --health-cmd="/oasis-node debug control wait-ready -a unix:/serverdir/node/net-runner/network/client-0/internal.sock"
          --health-start-period=90s
    steps:
      - name: attempt to connect to sapphire-dev-ci
        run: curl -kv http://sapphire-dev-ci:8545/ || true
      - name: attempt to connect to sapphire-dev-ci via localhost
        run: curl -kv http://127.0.0.1:8545/ || true
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm --filter '@oasisprotocol/sapphire-*' install
      - name: Build JS client
        working-directory: clients/js
        run: pnpm build
      - name: Build hardhat integration
        working-directory: integrations/hardhat
        run: pnpm build
      - name: hardhat test contracts
        working-directory: contracts
        run: pnpm hardhat test --network sapphire-dev-ci
      - name: pnpm install examples/hardhat-boilerplate
        working-directory: examples/hardhat-boilerplate
        run: pnpm install
      - name: hardhat test examples/hardhat-boilerplate
        working-directory: examples/hardhat-boilerplate
        run: pnpm hardhat test --network sapphire_localnet
