name: publish

on:
  push:
    tags:
      - clients/js/v[0-9]\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?
      - contracts/v[0-9]\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?
      - integrations/ethers-v6/v[0-9]\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?
      - integrations/hardhat/v[0-9]\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?
      - integrations/viem-v2/v[0-9]\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?
      - integrations/wagmi-v2/v[0-9]\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: true
      - name: Build JS client
        working-directory: clients/js
        run: pnpm build
      - name: Build ethers-v6 integration
        working-directory: integrations/ethers-v6
        run: pnpm build
      - name: Build hardhat integration
        working-directory: integrations/hardhat
        run: pnpm build
      - name: Build Viem integration
        working-directory: integrations/viem-v2
        run: pnpm build
      - name: Build Wagmi integration
        working-directory: integrations/wagmi-v2
        run: pnpm build
      - name: Extract package from tag
        id: extract-tag
        run: |
          echo "NPM_PACKAGE=$(echo ${{ github.ref_name }} | grep -oE '(clients/js|contracts|integrations/(hardhat|wagmi-v2|viem-v2))')" >> $GITHUB_OUTPUT
      - name: Publish ${{ github.ref_name }} to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          # Build runs as a prepublish script
          ignore-scripts: false
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ steps.extract-tag.outputs.NPM_PACKAGE }}
