# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: release

# Trigger the workflow when:
on:
  # A push occurs to one of the matched tags.
  push:
    tags:
      # For more details on GitHub Actions' pattern match syntax, see:
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags.
      - 'v[0-9]+.[0-9]+*'

jobs:

  prepare-release-runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Build tagged release, elf
        id: build-elf
        uses: oasisprotocol/oasis-sdk/.github/actions/hash-rust@main
        with:
          image: oasisprotocol/runtime-builder:main
          binaries: sapphire-paratime
          clean: no

      - name: Create the Oasis Runtime Container
        run: |
          go install github.com/oasisprotocol/oasis-sdk/tools/orc@latest
          orc init ${RUNTIME_EXECUTABLE}
        env:
          RUNTIME_EXECUTABLE: ${{ github.workspace }}/${{ steps.build-elf.outputs.build-path }}/sapphire-paratime

      - name: Publish the release
        uses: ncipollo/release-action@v1
        with:
          artifacts: sapphire-paratime.orc
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true

  prepare-release-encrypting-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Build tagged release, elf
        id: build-elf
        uses: oasisprotocol/oasis-sdk/.github/actions/hash-rust@main
        with:
          image: oasisprotocol/runtime-builder:main
          binaries: sapphire-encrypting-proxy
          clean: no

      - name: Publish the release
        uses: ncipollo/release-action@v1
        with:
          artifacts: sapphire-encrypting-proxy
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
